version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33066:33066
    restart: always
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pa$$worD"
      MYSQL_DATABASE: "meetingDB"
      MYSQL_USER: "meeting-name"
      MYSQL_PASSWORD: "testPassword"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3


  # backend port 8000 in .
  meeting-backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    environment:
      - MYSQL_HOST

   

  # frontend port 8080 in ./meeting-app
  meeting-app:
    build: ./meeting-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - meeting-backend

