version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33066:33066
    restart: always
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5


  # backend port 8000 in .
  meeting-backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    environment:
      - MYSQL_HOST
    command: sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
   

  # frontend port 8080 in ./meeting-app
  meeting-app:
    build: ./meeting-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - meeting-backend
    links:
      - meeting-backend
    environment:
      - backendHostPlusPort

