# Generated by Django 4.1 on 2022-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting_app_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinguser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
