# Generated by Django 4.1 on 2022-09-05 07:22

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations
from meeting_app_backend.models import MeetingUser, Role


def add_user(apps, schema_editor):
    User: MeetingUser = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    User.objects.create(
        email="admin@example.com",
        password=make_password("testPassword123"),
        role=Role.ADMIN,
        username="adminTest",
        is_superuser=True,
        is_staff=True,
    )
    User.objects.create(
        email="user@example.com",
        password=make_password("testPassword123"),
        role=Role.USER,
        username="userTest",
        is_superuser=False,
        is_staff=False,
    )


def delete_user(apps, schema_editor):
    User: MeetingUser = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meeting_app_backend", "0002_meetinguser_role"),
    ]

    operations = [migrations.RunPython(add_user, delete_user)]
