# Generated by Django 4.1 on 2022-09-05 08:18

from django.db import migrations
from ..models import Topic, TopicComment


# class Topic(models.Model):
#     topicText = models.CharField(max_length=255, blank=False, null=False, unique=True)
#     createdAt = models.DateTimeField(auto_now_add=True)

#     def __str__(self) -> str:
#         return self.topicText


# class TopicComment(models.Model):
#     topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
#     commentText = models.CharField(max_length=255, blank=False, null=False)
#     createdAt = models.DateTimeField(auto_now_add=True)

#     def __str__(self) -> str:
#         return self.commentText


def create_sample_data(apps, schema_editor):
    topic1 = Topic.objects.create(topicText="Topic 1")
    topic2 = Topic.objects.create(topicText="Topic 2")
    topic3 = Topic.objects.create(topicText="Topic 3")

    TopicComment.objects.create(topic=topic1, commentText="Comment 1")
    TopicComment.objects.create(topic=topic1, commentText="Comment 2")
    TopicComment.objects.create(topic=topic1, commentText="Comment 3")

    TopicComment.objects.create(topic=topic2, commentText="Comment 4")
    TopicComment.objects.create(topic=topic2, commentText="Comment 5")
    TopicComment.objects.create(topic=topic2, commentText="Comment 6")

    TopicComment.objects.create(topic=topic3, commentText="Comment 7")
    TopicComment.objects.create(topic=topic3, commentText="Comment 8")
    TopicComment.objects.create(topic=topic3, commentText="Comment 9")


def delete_sample_data(apps, schema_editor):
    Topic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meeting_app_backend", "0003_add_user"),
    ]

    operations = [
        migrations.RunPython(create_sample_data, delete_sample_data),
    ]
